# Generated by Django 3.1.4 on 2020-12-30 11:41

from django.db import migrations, models
import django.utils.timezone
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=255, unique=True, validators=[game.models.validate_password])),
                ('room_id', models.CharField(max_length=255)),
                ('players', models.IntegerField(default=0, validators=[game.models.validate_player_count])),
            ],
        ),
    ]
